// <auto-generated />
using System;
using EduTechPlus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduTechPlus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduTechPlus.Api.Models.AlumnoDetalle", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ColegioId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("ColegioId");

                    b.HasIndex("GrupoId");

                    b.ToTable("AlumnoDetalles");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Colegio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colegios");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("Nombre", "Turno", "ColegioId")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Leccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreadorProfesorId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsOficial")
                        .HasColumnType("boolean");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadorProfesorId");

                    b.HasIndex("TemaId");

                    b.ToTable("Lecciones");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadorProfesorId")
                        .HasColumnType("integer");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsOficial")
                        .HasColumnType("boolean");

                    b.Property<string>("RespuestaCorrecta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreadorProfesorId");

                    b.HasIndex("TemaId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ProfesorDetalle", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ColegioId")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("ColegioId");

                    b.ToTable("ProfesorDetalles");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ProfesorGrupoMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfesorDetalleUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfesorDetalleUsuarioId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("ProfesorGrupoMaterias");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreadorProfesorId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsOficial")
                        .HasColumnType("boolean");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadorProfesorId");

                    b.HasIndex("TemaId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.QuizPregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizPreguntas");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ResultadoQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPreguntas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("QuizId");

                    b.ToTable("ResultadosQuiz");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreadorProfesorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsOficial")
                        .HasColumnType("boolean");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadorProfesorId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.AlumnoDetalle", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.Usuario", "Usuario")
                        .WithOne("AlumnoDetalle")
                        .HasForeignKey("EduTechPlus.Api.Models.AlumnoDetalle", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Grupo", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Colegio", "Colegio")
                        .WithMany("Grupos")
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Leccion", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Usuario", "CreadorProfesor")
                        .WithMany()
                        .HasForeignKey("CreadorProfesorId");

                    b.HasOne("EduTechPlus.Api.Models.Tema", "Tema")
                        .WithMany("Lecciones")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadorProfesor");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Pregunta", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Usuario", "CreadorProfesor")
                        .WithMany()
                        .HasForeignKey("CreadorProfesorId");

                    b.HasOne("EduTechPlus.Api.Models.Tema", "Tema")
                        .WithMany("Preguntas")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadorProfesor");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ProfesorDetalle", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Colegio", "Colegio")
                        .WithMany()
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.Usuario", "Usuario")
                        .WithOne("ProfesorDetalle")
                        .HasForeignKey("EduTechPlus.Api.Models.ProfesorDetalle", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ProfesorGrupoMateria", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Grupo", "Grupo")
                        .WithMany("Profesores")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.Materia", "Materia")
                        .WithMany("ProfesoresPorGrupo")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.ProfesorDetalle", null)
                        .WithMany("ProfesoresGruposMaterias")
                        .HasForeignKey("ProfesorDetalleUsuarioId");

                    b.HasOne("EduTechPlus.Api.Models.Usuario", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Quiz", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Usuario", "CreadorProfesor")
                        .WithMany()
                        .HasForeignKey("CreadorProfesorId");

                    b.HasOne("EduTechPlus.Api.Models.Tema", "Tema")
                        .WithMany("Quizzes")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadorProfesor");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.QuizPregunta", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.Quiz", "Quiz")
                        .WithMany("QuizPreguntas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ResultadoQuiz", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.AlumnoDetalle", "Alumno")
                        .WithMany("ResultadosQuiz")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTechPlus.Api.Models.Quiz", "Quiz")
                        .WithMany("Resultados")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Tema", b =>
                {
                    b.HasOne("EduTechPlus.Api.Models.Usuario", "CreadorProfesor")
                        .WithMany()
                        .HasForeignKey("CreadorProfesorId");

                    b.HasOne("EduTechPlus.Api.Models.Materia", "Materia")
                        .WithMany("Temas")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadorProfesor");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.AlumnoDetalle", b =>
                {
                    b.Navigation("ResultadosQuiz");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Colegio", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Grupo", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Materia", b =>
                {
                    b.Navigation("ProfesoresPorGrupo");

                    b.Navigation("Temas");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.ProfesorDetalle", b =>
                {
                    b.Navigation("ProfesoresGruposMaterias");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Quiz", b =>
                {
                    b.Navigation("QuizPreguntas");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Tema", b =>
                {
                    b.Navigation("Lecciones");

                    b.Navigation("Preguntas");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("EduTechPlus.Api.Models.Usuario", b =>
                {
                    b.Navigation("AlumnoDetalle");

                    b.Navigation("ProfesorDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
